export const ActionTypes = {
    // AuthStore
    AUTH_LOGIN: "AUTH_LOGIN",
    AUTH_LOGOUT: "AUTH_LOGOUT",

    // CurrentUserStore
    USER_UPDATE: "USER_UPDATE",
    USER_FETCH_START: "USER_FETCH_START",
    USER_FETCH_SUCCESS: "USER_FETCH_SUCCESS",
    USER_FETCH_FAILURE: "USER_FETCH_FAILURE",

    // UpcomingWatchEventStore
    UPCOMING_EVENT_FETCH_START: "UPCOMING_EVENT_FETCH_START",
    UPCOMING_EVENT_FETCH_SUCCESS: "UPCOMING_EVENT_FETCH_SUCCESS",
    UPCOMING_EVENT_FETCH_FAILURE: "UPCOMING_EVENT_FETCH_FAILURE",

    UPCOMING_EVENT_NOTIFY_TOGGLE: "UPCOMING_EVENT_NOTIFY_TOGGLE",

    // LessonsStore
    LESSONS_FETCH_START: "LESSONS_FETCH_START",
    LESSONS_FETCH_SUCCESS: "LESSONS_FETCH_SUCCESS",
    LESSONS_FETCH_FAILURE: "LESSONS_FETCH_FAILURE",

    LESSONS_FILTER: "LESSONS_FILTER",
    LESSONS_CLEAR_FILTER: "LESSONS_CLEAR_FILTER",

    // TeacherStore
    TEACHERS_FETCH_START: "TEACHERS_FETCH_START",
    TEACHERS_FETCH_SUCCESS: "TEACHERS_FETCH_SUCCESS",
    TEACHERS_FETCH_FAILURE: "TEACHERS_FETCH_FAILURE",

    TEACHERS_FILTER: "TEACHERS_FILTER",
    TEACHERS_CLEAR_FILTER: "TEACHERS_CLEAR_FILTER",

    // UserProfileStore
    USER_PROFILE_FETCH_START: "USER_PROFILE_FETCH_START",
    USER_PROFILE_FETCH_SUCCESS: "USER_PROFILE_FETCH_SUCCESS",
    USER_PROFILE_FETCH_FAILURE: "USER_PROFILE_FETCH_FAILURE",
    
    // WatchRequestStore
    WATCH_REQUEST_FETCH_START: "WATCH_REQUEST_FETCH_START",
    WATCH_REQUEST_FETCH_SUCCESS: "WATCH_REQUEST_FETCH_SUCCESS",
    WATCH_REQUEST_FETCH_FAILURE: "WATCH_REQUEST_FETCH_FAILURE",

    WATCH_REQUEST_REMOVE: "WATCH_REQUEST_REMOVE",

    // LessonSearchStore
    LESSON_SEARCH_RESULT: "LESSON_SEARCH_RESULT",
    LESSON_SEARCH_FILTER_CHANGE: "LESSON_SEARCH_RESULT",

    // AssessmentsStore
    ASSESSMENTS_FETCH_START: "ASSESSMENTS_FETCH_START",
    ASSESSMENTS_FETCH_SUCCESS: "ASSESSMENTS_FETCH_SUCCESS",
    ASSESSMENTS_FETCH_FAILURE: "ASSESSMENTS_FETCH_FAILURE",

    // AssessmentScoreStore
    ASSESSMENT_SCORE_FETCH_START: "ASSESSMENT_SCORE_FETCH_START",
    ASSESSMENT_SCORE_FETCH_SUCCESS: "ASSESSMENT_SCORE_SET_VALUES",
    ASSESSMENT_SCORE_FETCH_FAILURE: "ASSESSMENT_SCORE_FETCH_FAILURE",
    ASSESSMENT_SCORE_SET_STUDENT_SCORE: "ASSESSMENT_SCORE_SET_STUDENT_SCORE",
    ASSESSMENT_SCORE_SET_MARKER: "ASSESSMENT_SCORE_SET_MARKER",
    ASSESSMENT_SCORE_SET_MARKER_ALL: "ASSESSMENT_SCORE_SET_MARKER_ALL",
    ASSESSMENT_SCORE_CLEAR_STUDENT_SCORE: "ASSESSMENT_SCORE_CLEAR_STUDENT_SCORE",
    ASSESSMENT_SCORE_ADD_STUDENT_SCORE_FLAG: "ASSESSMENT_SCORE_ADD_STUDENT_SCORE_FLAG",
    ASSESSMENT_SCORE_REMOVE_STUDENT_SCORE_FLAG: "ASSESSMENT_SCORE_REMOVE_STUDENT_SCORE_FLAG",
    ASSESSMENT_SCORE_DISMISS_WARNING: "ASSESSMENT_SCORE_DISMISS_WARNING",
    ASSESSMENT_SCORE_OPEN_FLAG_DROPDOWN: "ASSESSMENT_SCORE_OPEN_FLAG_DROPDOWN",
    ASSESSMENT_SCORE_OPEN_TEACHER_DROPDOWN: "ASSESSMENT_SCORE_OPEN_TEACHER_DROPDOWN",
    ASSESSMENT_SCORE_CLOSE_TEACHER_DROPDOWN: "ASSESSMENT_SCORE_CLOSE_TEACHER_DROPDOWN",
    
    // TeacherSearchStore
    TEACHER_SEARCH_RESULT: "TEACHER_SEARCH_RESULT",
    TEACHER_SEARCH_FILTER_CHANGE: "TEACHER_SEARCH_FILTER_CHANGE",

    // AssessmentCompareStore
    ASSESSMENT_COMPARE_FETCH_START: "ASSESSMENT_COMPARE_FETCH_START",
    ASSESSMENT_COMPARE_FETCH_SUCCESS: "ASSESSMENT_COMPARE_FETCH_SUCCESS",
    ASSESSMENT_COMPARE_FETCH_FAILURE: "ASSESSMENT_COMPARE_FETCH_FAILURE",
    ASSESSMENT_COMPARE_APPLY_VIRTUAL_VIEW: "ASSESSMENT_COMPARE_APPLY_VIRTUAL_VIEW",
    ASSESSMENT_COMPARE_CLEAR_VIRTUAL_VIEW: "ASSESSMENT_COMPARE_CLEAR_VIRTUAL_VIEW",
    ASSESSMENT_COMPARE_FETCH_COMMENTS_START: "ASSESSMENT_COMPARE_FETCH_COMMENTS_START",
    ASSESSMENT_COMPARE_FETCH_COMMENTS_SUCCESS: "ASSESSMENT_COMPARE_FETCH_COMMENTS_SUCCESS",
    ASSESSMENT_COMPARE_FETCH_COMMENTS_FAILURE: "ASSESSMENT_COMPARE_FETCH_COMMENTS_FAILURE",
    ASSESSMENT_COMPARE_ADD_COMMENT: "ASSESSMENT_COMPARE_ADD_COMMENT",

    FILTER_ASSESSMENT_INIT: "FILTER_ASSESSMENT_INIT",
    FILTER_ASSESSMENT_CHANGE: "FILTER_ASSESSMENT_CHANGE"
}